name: Documentation Generation & Deployment
run-name: "Génération et publication de documentation"

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 0'  # Tous les dimanches à minuit UTC
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.x'

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress

      - name: Configure Composer allow-plugins
        run: composer global config --no-plugins allow-plugins.symfony/flex true

      - name: Install phpDocumentor
        run: composer global require phpdocumentor/phpdocumentor

      - name: Generate Documentation
        run: vendor/bin/phpdoc -d . -t docs

      - name: Deploy Documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
